package dev.buildcli.infrastructure;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;
import java.util.stream.IntStream;

/** The tables of the state database and how an older database is brought up to date, for SQLite and H2. */
final class StateSchema {
    /** Index i migrates the schema from version i to version i+1. Never edit a released entry; append a new one. */
    static final List<List<String>> MIGRATIONS = List.of(
            List.of(
                    // the "team" column holds the name of the group (or agent) a run was for; kept so existing databases need no migration
                    "CREATE TABLE runs (id TEXT PRIMARY KEY, team TEXT NOT NULL, request TEXT NOT NULL,"
                            + " started_at TEXT NOT NULL, finished_at TEXT, status TEXT NOT NULL, summary TEXT)",
                    "CREATE TABLE tasks (run_id TEXT NOT NULL, id INTEGER NOT NULL, parent_id INTEGER, from_agent TEXT NOT NULL,"
                            + " to_agent TEXT NOT NULL, objective TEXT NOT NULL, brief TEXT NOT NULL, status TEXT NOT NULL,"
                            + " result TEXT, attempts INTEGER NOT NULL, tokens INTEGER NOT NULL, updated_at TEXT NOT NULL,"
                            + " PRIMARY KEY (run_id, id))",
                    "CREATE TABLE events (id INTEGER PRIMARY KEY AUTOINCREMENT, run_id TEXT NOT NULL, ts TEXT NOT NULL,"
                            + " type TEXT NOT NULL, task_id INTEGER NOT NULL, agent TEXT, payload TEXT,"
                            + " input_tokens INTEGER NOT NULL DEFAULT 0, output_tokens INTEGER NOT NULL DEFAULT 0)",
                    "CREATE INDEX events_by_run ON events (run_id, id)"),
            List.of(
                    "CREATE TABLE chat_messages (id INTEGER PRIMARY KEY, thread TEXT NOT NULL, kind TEXT NOT NULL,"
                            + " author TEXT NOT NULL, text TEXT NOT NULL, at TEXT NOT NULL, state TEXT NOT NULL,"
                            + " attachments TEXT NOT NULL DEFAULT '', position INTEGER NOT NULL DEFAULT 0)",
                    "CREATE INDEX chat_messages_by_position ON chat_messages (position, id)"),
            List.of(
                    "CREATE TABLE file_changes (message_id INTEGER NOT NULL, seq INTEGER NOT NULL, agent TEXT NOT NULL,"
                            + " path TEXT NOT NULL, existed INTEGER NOT NULL, before_text TEXT, after_text TEXT,"
                            + " PRIMARY KEY (message_id, seq))"));

    /** The schema version this build writes. */
    static final int VERSION = MIGRATIONS.size();


    /** The SQL of a migration for this engine: H2 has no AUTOINCREMENT and keeps long text in VARCHAR. */
    static String dialect(String sql, boolean h2) {
        return h2 ? sql.replace("INTEGER PRIMARY KEY AUTOINCREMENT", "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY")
                .replaceAll("\\bTEXT\\b", "VARCHAR") : sql;
    }

    static int readVersion(Connection connection, boolean h2) throws SQLException {
        try (Statement st = connection.createStatement()) {
            if (h2) {
                st.execute("CREATE TABLE IF NOT EXISTS buildcli_schema (version INT NOT NULL)");
                try (ResultSet rs = st.executeQuery("SELECT version FROM buildcli_schema")) {
                    return rs.next() ? rs.getInt(1) : 0;
                }
            }
            try (ResultSet rs = st.executeQuery("PRAGMA user_version")) {
                return rs.next() ? rs.getInt(1) : 0;
            }
        }
    }

    private static final List<String> SET_USER_VERSION = IntStream.rangeClosed(0, VERSION).mapToObj(v -> "PRAGMA user_version=" + v).toList();

    private static void writeVersion(Statement st, boolean h2, int version) throws SQLException {
        if (h2) {
            st.execute("DELETE FROM buildcli_schema");
            try (PreparedStatement insert = st.getConnection().prepareStatement("INSERT INTO buildcli_schema (version) VALUES (?)")) {
                insert.setInt(1, version);
                insert.executeUpdate();
            }
        } else {
            // PRAGMA takes no parameters: one fixed statement per known version, picked by index, never built from input
            st.execute(SET_USER_VERSION.get(version));
        }
    }

    static void migrate(Connection connection, boolean h2) throws SQLException {
        int current = readVersion(connection, h2);
        if (current > VERSION) {
            throw new IllegalStateException("the state database is schema version " + current + " but this BuildCLI only"
                    + " understands up to " + VERSION + "; upgrade BuildCLI (the database was not modified)");
        }
        for (int v = current; v < VERSION; v++) {
            connection.setAutoCommit(false);
            try (Statement st = connection.createStatement()) {
                for (String sql : MIGRATIONS.get(v)) {
                    st.execute(dialect(sql, h2));
                }
                writeVersion(st, h2, v + 1);
                connection.commit();
            } catch (SQLException e) {
                connection.rollback();
                throw e;
            } finally {
                connection.setAutoCommit(true);
            }
        }
    }

    private StateSchema() { }
}
